### ISSUE TITLE
Location not appearing at address in public view

### ISSUE THREAD

**Issue by mkane2** [CPHDH/Curatescape#44]
I have several locations which are correctly located in the edit/admin view map interface, but in the public view the map just has a continual loading animation and doesn't find the location.  Example: http://www.albanywalksforhealth.com/items/show/43  This happens for locations both with addresses entered using the Find button and for manually placed locations, and happens on multiple browsers.  Other locations added by the same users do appear on the map without issue, and I can't find a pattern for the locations which aren't being located in public view.  Is there a trick to getting these to appear in public view?

**Comment by ebellempire** [comment]
Hi, I think the issue is related to the line breaks in your street address. Try removing them and see if it works.

**Comment by mkane2** [comment]
Thanks for the suggestion.  It doesn't appear to be line breaks in the address; the loading problem still happens with manually placed map pins and for addresses that are directly entered or corrected to have no line breaks.  It also persists whether there's commas in the address or not.

**Comment by ebellempire** [comment]
Just to be clear, you removed the line break from the _Item Type Metadata > Curatescape Story > Street Address_ field that reads "107 State Street Albany, New York 12207" (it looks like it's still there)? When that field has a value it is placed in the map infowindow. It is _separate_ from where you enter the location on the map (i.e. in the _Geolocation_ tab).

**Comment by ebellempire** [comment]
By the way, this is a known bug. I just need to get around to fixing it (by stripping out line breaks and carriage returns before building the map infowindows).

**Comment by mkane2** [comment]
OK, no, I had corrected the Geolocation tab address, didn't realize that one would over ride the other.  It does look like correcting the line breaks in the Item Type Metadata did correct it, thank you.

**Comment by ebellempire** [comment]
Great! I'll try to get a permanent fix out for this soon.
