### ISSUE TITLE
Images on map markers appear awkward when cropped from bottom

### ISSUE THREAD

**Issue by elipousson** [CPHDH/Curatescape#46]
The images in the new map markers look good but most of our images do not look good when the bottom edge of the image is cropped out. Maybe the image bubbles should be centered? Here are a couple of examples of what it looks like:

![screen shot 2016-05-13 at 2 06 13 pm](https://cloud.githubusercontent.com/assets/931136/15257400/24f8edee-1914-11e6-8aa5-3d7aeace068e.png)
[True Grit Statue](http://explore.baltimoreheritage.org/items/show/544)

![screen shot 2016-05-13 at 2 09 00 pm](https://cloud.githubusercontent.com/assets/931136/15257427/4793b564-1914-11e6-8f8e-52b6c45576f0.png)
[First & Franklin Presbyterian Church](http://explore.baltimoreheritage.org/items/show/56)

![screen shot 2016-05-13 at 2 09 52 pm](https://cloud.githubusercontent.com/assets/931136/15257452/656eb7fa-1914-11e6-9be5-ea97ddae7826.png)
[The Patterson](http://explore.baltimoreheritage.org/items/show/512)

**Comment by ebellempire** [comment]
I'll adjust this in the next update. In the meantime, you can add the following CSS to theme settings:

`.curatescape-infowindow-image{background-position:center}`

**Comment by ebellempire** [comment]
Fixed in theme repo. https://github.com/CPHDH/theme-curatescape/commit/2375cfc47277219c1737bac2e9f343b7993e5f57
