### ISSUE TITLE
Map not loading over HTTPS

### ISSUE THREAD

**Issue by elipousson** [CPHDH/Curatescape#47]
I set up HTTPS for battleofbaltimore.org a few weeks ago but just noticed that none of the maps are loading over the secure connection. If I switch back to HTTP the maps load just fine.

![screen shot 2016-06-03 at 8 56 33 am](https://cloud.githubusercontent.com/assets/931136/15779248/363091d8-2969-11e6-95fd-248c00bb0145.png)

**Comment by ebellempire** [comment]
Console log:

> Mixed Content: The page at 'https://www.battleofbaltimore.org/' was loaded over HTTPS, but requested an insecure script 'http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js'. This request has been blocked; the content must be served over HTTPS.

Try editing `common/header.php` on lines 70-71, replacing `http://` with just `//`.

I'll update the repo.
