### ISSUE TITLE
Non-public stories appear on tour map

### ISSUE THREAD

**Issue by elipousson** [CPHDH/Curatescape#49]
![screen shot 2016-09-26 at 3 23 12 pm](https://cloud.githubusercontent.com/assets/931136/18848626/3e2d5076-83fd-11e6-97f6-199f080c19d6.png)

Here is an example from [a tour I just set up on Explore Baltimore Heritage](http://explore.baltimoreheritage.org/tours/show/21). Map markers appear for stories that are not marked as public. We sometimes add non-public stories to tours if we know the story will eventually be added to the site.

**Comment by ebellempire** [comment]
Fixed with https://github.com/CPHDH/theme-curatescape/commit/9b7d016969501cd871c7f64376e630711dd27675
