### ISSUE TITLE
Map Pins not appearing on map with php 5.3.3

### ISSUE THREAD

**Issue by joe-e-brown** [CPHDH/Curatescape#51]
[browse.mjson.php.patch.txt](https://github.com/CPHDH/Curatescape/files/1307675/browse.mjson.php.patch.txt)
I maintain an omeka 2.5 blog which features a map with multiple pins on the front page.
Those pins don't appear when I upgrade curatescapejson to the version on the master branch.
the issue appears to be line 118 in the file CuratescapeJSON/views/shared/items/browse.mjson.php.
The following code fails to run: $postProcessed = [];
After replacing it with this line: $postProcessed = array();
Curatescape JSON works properly & map pins are displayed.
This work son both php 5.4.16 and 5.3.3

**Comment by joe-e-brown** [comment]
I have made a mistake.
This should've been created under CPHDH/CuratescapeJSON, not under CPHDH/Curatescape.
I'll fix this promptly.

**Comment by joe-e-brown** [comment]
I see this is the only place for issues. Reopening issue.

**Comment by joe-e-brown** [comment]
[browse.mjson.php.patch.txt](https://github.com/CPHDH/Curatescape/files/1307717/browse.mjson.php.patch.txt)

This patch edited for viewing on Microsoft platform.

**Comment by csudigitalhumanities** [comment]
Thanks for the heads up, @joe-e-brown!

https://github.com/CPHDH/CuratescapeJSON/commit/c58f0c89816854ee1e1fabcfbef4126404fdcd9b
