### ISSUE TITLE
jQuery mmenu Missing - Actually incorrectly referenced

### ISSUE THREAD

**Issue by mprythero** [CPHDH/Curatescape#53]
Hello!
I've got what I believe to be a relatively simple issue to fix, but I thought you might just want to know about it too.

So my project isn't in the base of the host folder, it's in one folder beneath it for testing purposes. I recently discovered that I can't use my menu button on either desktop or through my mobile phone and when clicked, the console logs the following:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.XXXXXXXXX.com/themes/curatescape/javascripts/jquery.mmenu/jquery.mmenu.all.js

The problem here is that it should actually be looking for the folder as such:
http://www.XXXXXXXXX.com/greeley/themes/curatescape/javascripts/jquery.mmenu/jquery.mmenu.all.js

What do I need to change to make sure it gets referenced to the correct folder?

Thanks!
Matt

**Comment by ebellempire** [comment]
http://forum.curatescape.org/t/jquery-mmenu-missing-actually-incorrectly-referenced/251/2
