### ISSUE TITLE
Does the API for getting tours info exist?

### ISSUE THREAD

**Issue by drphamwit** [CPHDH/Curatescape#54]
Hi there,

We need to get tour info but do not know what API to call. Does the API for tours actually exist or not? Please advise on how to get tour info and what API call should look like.

Thanks,

PS: I was referred to you by the Omeka team.

**Comment by ebellempire** [comment]
Hi, in what context are you trying to get tours? JavaScript or PHP?

For JS, you can get a JSON feed for tours and items by adding `?output=mobile-json` to the URL, e.g. `/tours/browse?output=mobile-json`.

For PHP, check the Curatescape theme files at `themes/curatescape/tour-builder/tours/` for typical usage, or see the `mh_display_homepage_tours()` function in `custom.php` for an example of how to grab tours directly from the database (for example to use on the homepage).

By the way, this kind of question can be better addressed on the forum: https://forum.curatescape.org/

**Comment by drphamwit** [comment]
> ?output=mobile-json

Thanks for your quick response! /tours/browse?output=mobile-json is exactly what we need. I will post in the forum instead next time.
