### ISSUE TITLE
Accept non-legacy Google Analytics codes

### ISSUE THREAD

**Issue by coherit** [CPHDH/Curatescape#55]
Feature Request / Update to Analytics handling:
Curatescape seems to only accept legacy (universal analytics) Google Analytic IDs, which begin with UA. The new generation of [Google Analytics 4](https://support.google.com/analytics/answer/10089681) IDs start with a G, but are not supported by the current version of Curatescape (at least through the GUI). As more entities begin adopting GA4 and using global site IDs, this may become problematic.

**Comment by ebellempire** [comment]
Fix will be in next release
