### ISSUE TITLE
Ability to sort Related Resources entries

### ISSUE THREAD

**Issue by jbretmaney** [CPHDH/Curatescape#57]
_Feature request_. We are using the Related Resources section as a bibliography for articles (here's [an example](https://discover.latinocatskills.com/items/show/22)) and would find it useful if we could change the order of individual entries afterwards to keep the full list alphabetized. At present, the entries appear in the order in which they were inputted. This means that when a new resource entry is added, the full list often needs to be re-done to maintain alphabetization (that is, unless we've missed something). Thanks for considering!

**Comment by ebellempire** [comment]
Hi @jbretmaney, this is more of an Omeka feature request. I've also felt the pain of not being able to easily re-order metadata fields. 

If you have the ability/inclination to edit the code yourself, you'd want to change the `rl_related_links()` function in the theme's `custom.php` file around line 1196. Just adding a new line like `sort($relations);` should automatically alphabetize the output on the frontend so you don't need to manually re-order the entries.

**Comment by jbretmaney** [comment]
Thank you for these clarifications, @ebellempire. I should have known you would already have remedied this, had it been possible.
